#Expyriment 0.9.0 (Python 2.7.15), .xpe-file, coding: UTF-8
#date: Wed Sep 19 2018 14:19:01
#sha1: a911c6
#modules: 
#display: size=(1440, 900), window_mode=False, open_gl=2
#os: ('Darwin', 'Lynns-MacBook-Air.local', '17.2.0', 'Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64', 'x86_64', 'i386')
Time,Type,Event,Value,Detail,Detail2
13249,design,log,
#design: #exp: First Experiment
#design: block_cnt,block_id,trial_cnt,trial_id
13249,design,logged,
13249,Experiment,started
13324,stdout,received,'videos/7ZnijRlK5-E.000.mp4'
14507,stdout,received,'size 1 (1280, 720)'
14508,Video,playing,videos/zEyRyTnIw5I.004.mp4
14510,stderr,received,'Traceback (most recent call last):'
14510,stderr,received,'  File "/Users/lynn/Desktop/AMT Research assistantship/AMT_results/AMTproject_consistency/Experiment_100pairs.py", line 90, in <module>'
14511,stderr,received,'    while not my_video1.new_frame_available or not my_video2.new_frame_available:'
14511,stderr,received,"NameError: name 'my_video2' is not defined"
