#Expyriment 0.9.0 (Python 2.7.15), .xpe-file, coding: UTF-8
#date: Wed Sep 19 2018 22:51:40
#sha1: 973f90
#modules: 
#display: size=(1440, 900), window_mode=False, open_gl=2
#os: ('Darwin', 'Lynns-MacBook-Air.local', '17.2.0', 'Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64', 'x86_64', 'i386')
Time,Type,Event,Value,Detail,Detail2
18390,design,log,
#design: #exp: First Experiment
#design: block_cnt,block_id,trial_cnt,trial_id
18390,design,logged,
18390,Experiment,started
18410,stderr,received,'Traceback (most recent call last):'
18410,stderr,received,'  File "/Users/lynn/Desktop/AMT Research assistantship/AMT_results/AMTproject_consistency/Experiment_100pairs.py", line 33, in <module>'
18411,stderr,received,'    my_video = my_video(video_pair)'
18411,stderr,received,"TypeError: 'Video' object is not callable"
